site_name: App Template
site_description: Yet another template.

repo_name: tygourm/app-template
repo_url: https://github.com/tygourm/app-template

theme:
  name: material

  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - toc.follow

  palette:
    # System palette
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light palette
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark palette
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Ubuntu
    code: Ubuntu Mono

  logo: img/favicon-light.svg
  favicon: img/favicon.svg
  icon:
    repo: material/github

plugins:
  - offline
  - privacy
  - search

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: index.md
  - Changelog: CHANGELOG.md
  - Release Engineering: RELENG.md
